name: 'TEST: Arch Linux'

on:
  workflow_dispatch:
        inputs: 
            client:
                description: 'Client to Test'
                type: choice
                options:
                - cnspec
                - cnquery



jobs:
    install-sh-apt:
        runs-on: ubuntu-latest
        #strategy:
        #    matrix:
        #      client: ['cnquery', 'cnspec']
        steps:
            - uses: actions/checkout@v3
            
            - name: Install cnquery on Arch Linux
              run: |
                  docker run --rm -v $(pwd):/work -w /work archlinux:latest \
                  bash -c "pacman -Syu --noconfirm && \
                            pacman -S --noconfirm base-devel git &&  \
                            cd /tmp && \
                            useradd test && \
                            su test -c 'git clone https://aur.archlinux.org/cnquery && cd cnquery && makepkg' && \
                            cd cnquery && \
                            pacman -U --noconfirm cnquery-*.zst && \
                            cnquery version"
