name: 'TEST: Arch Linux'

on:
  workflow_dispatch:

jobs:
    install-sh-apt:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              client: ['cnquery', 'cnspec']
        steps:
            - uses: actions/checkout@v3
            
            - name: Install ${{ matrix.client }} on Arch Linux
              run: |
                  docker run --rm -v $(pwd):/work -w /work archlinux:latest \
                  bash -c "pacman -Syu --noconfirm && \
                            pacman -S --noconfirm base-devel git &&  \
                            cd /tmp && \
                            useradd test && \
                            su test -c \"git clone https://aur.archlinux.org/ ${{ matrix.client }} && cd  ${{ matrix.client }} && makepkg\" && \
                            cd  ${{ matrix.client }} && \
                            pacman -U --noconfirm  ${{ matrix.client }}-*.zst && \
                            ${{ matrix.client }} version"
