name: 'TEST: macOS Package'

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to test'
        required: true
        default: '8.3.0'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test'
        required: true
        default: '8.3.0'

jobs:
    pkg:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - name: Download Package
              run: |
                curl -SL -O https://releases.mondoo.com/mondoo/${{ github.event.inputs.version }}/mondoo_${{ github.event.inputs.version }}_darwin_universal.pkg
            - name: Install Package
              run: |
                sudo installer -pkg mondoo_${{ github.event.inputs.version }}_darwin_universal.pkg -target /

            - name: Executing cnspec...
              run: |
                cnspec version